library(dplyr)
library(Seurat)
library(ggplot2) 
library(patchwork)

adult1.data <- Read10X(data.dir = "F:/Flex/bfx2530.M1.M1_1.cellranger_multi/M1_1/count/sample_filtered_feature_bc_matrix/")
adult2.data <- Read10X(data.dir = "F:/Flex/bfx2530.M2.M2_1.cellranger_multi/M2_1/count/sample_filtered_feature_bc_matrix/")
aged1.data <- Read10X(data.dir = "F:/Flex/bfx2530.M1.M1_2.cellranger_multi/M1_2/count/sample_filtered_feature_bc_matrix/")
aged2.data <- Read10X(data.dir = "F:/Flex/bfx2530.M2.M2_2.cellranger_multi/M2_2/count/sample_filtered_feature_bc_matrix/")
agedPLX1.data <- Read10X(data.dir = "F:/Flex/bfx2530.M1.M1_3.cellranger_multi/M1_3/count/sample_filtered_feature_bc_matrix/")
agedPLX2.data <- Read10X(data.dir = "F:/Flex/bfx2530.M2.M2_3.cellranger_multi/M2_3/count/sample_filtered_feature_bc_matrix/")
adult1 <- CreateSeuratObject(counts = adult1.data, project = "adult1", min.cells = 3, min.features = 200)
adult2 <- CreateSeuratObject(counts = adult2.data, project = "adult2", min.cells = 3, min.features = 200)
aged1 <- CreateSeuratObject(counts = aged1.data, project = "aged1", min.cells = 3, min.features = 200)
aged2 <- CreateSeuratObject(counts = aged2.data, project = "aged2", min.cells = 3, min.features = 200)
agedPLX1 <- CreateSeuratObject(counts = agedPLX1.data, project = "agedPLX1", min.cells = 3, min.features = 200)
agedPLX2 <- CreateSeuratObject(counts = agedPLX2.data, project = "agedPLX2", min.cells = 3, min.features = 200)
FlexPLX <- merge(adult1, y = c(adult2, aged1, aged2, agedPLX1, agedPLX2), add.cell.ids = c("adult1", "adult2", "aged1", "aged2", "agedPLX1", "agedPLX2"), project = "FlexPLX")
FlexPLX[["percent.mt"]] <- PercentageFeatureSet(FlexPLX, pattern = "^mt-")
VlnPlot(FlexPLX, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
FlexPLX <- JoinLayers(FlexPLX)
FlexPLX <- NormalizeData(FlexPLX, normalization.method = "LogNormalize", scale.factor = 10000)
FlexPLX <- FindVariableFeatures(FlexPLX, selection.method = "vst", nfeatures = 2000)
FlexPLX <- ScaleData(FlexPLX)
FlexPLX <- RunPCA(FlexPLX, features = VariableFeatures(object = FlexPLX))
ElbowPlot(FlexPLX)
FlexPLX <- FindNeighbors(FlexPLX, dims = 1:10)
FlexPLX <- FindClusters(FlexPLX, resolution = 0.5)
FlexPLX <- RunUMAP(FlexPLX, dims = 1:10)
DimPlot(FlexPLX, label = TRUE)
FlexPLX.markers <- FindAllMarkers(FlexPLX, only.pos = TRUE)

MGFlexPLX <- subset(FlexPLX, idents = c("2", "8", "9"))
MGFlexPLX <- subset(MGFlexPLX, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)
MGFlexPLX <- FindVariableFeatures(MGFlexPLX, selection.method = "vst", nfeatures = 2000)
MGFlexPLX <- ScaleData(MGFlexPLX)
MGFlexPLX <- RunPCA(MGFlexPLX, features = VariableFeatures(object = MGFlexPLX))
ElbowPlot(MGFlexPLX)
MGFlexPLX <- FindNeighbors(MGFlexPLX, dims = 1:10)
MGFlexPLX <- FindClusters(MGFlexPLX, resolution = 0.5)
MGFlexPLX <- RunUMAP(MGFlexPLX, dims = 1:10)
DimPlot(MGFlexPLX, label = TRUE)
MGFlexPLX.markers <- FindAllMarkers(MGFlexPLX, only.pos = TRUE)
MGFlexPLX <- subset(MGFlexPLX, idents = c("0", "1", "2", "5", "6", "9", "11"))
MGFlexPLX <- FindVariableFeatures(MGFlexPLX, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(MGFlexPLX)
MGFlexPLX <- ScaleData(MGFlexPLX, features = all.genes)
MGFlexPLX <- RunPCA(MGFlexPLX, features = VariableFeatures(object = MGFlexPLX))
ElbowPlot(MGFlexPLX)
MGFlexPLX <- FindNeighbors(MGFlexPLX, dims = 1:12)
MGFlexPLX <- FindClusters(MGFlexPLX, resolution = 1.4)
MGFlexPLX <- RunUMAP(MGFlexPLX, dims = 1:12)
DimPlot(MGFlexPLX, label = TRUE)
MGFlexPLX.markers <- FindAllMarkers(MGFlexPLX, only.pos = TRUE)
MGFlexPLX <- subset(MGFlexPLX, idents = c("16","17"), invert = TRUE)
MGFlexPLX <- RunUMAP(MGFlexPLX, dims = 1:12)
DimPlot(MGFlexPLX, label = TRUE)
FlexPLX.markers <- FindAllMarkers(FlexPLX, only.pos = TRUE)
new.cluster.ids <- c("HMG3", "HMG4", "HMG3", "HMG1", "HMG2", "HMG2", "WAM3", "WAM2", "HMG1", "HMG2", "WAM3", "HMG4", "HMG4", "CAM", "IRM", "WAM1", "HMG3")
names(new.cluster.ids) <- levels(MGFlexPLX)
MGFlexPLX <- RenameIdents(MGFlexPLX, new.cluster.ids)
levels(MGFlexPLX) <- c("HMG1", "HMG2", "HMG3", "HMG4", "CAM", "IRM", "WAM1", "WAM2", "WAM3") 
MGFlexPLX.markers <- FindAllMarkers(MGFlexPLX, only.pos = TRUE)
MGFlexPLX[["names"]] <- Idents(object = MGFlexPLX)
DimPlot(MGFlexPLX, cols = c("grey85", "yellowgreen", "violet", "yellow2", "brown3", "grey40", "red", "blue", "deepskyblue"), pt.size = 0.5)

Idents(MGFlexPLX) <- "orig.ident"
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `agedPLX2` = "agedPLX")
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `agedPLX1` = "agedPLX")
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `aged2` = "aged")
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `aged1` = "aged")
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `adult2` = "adult")
MGFlexPLX <- RenameIdents(object = MGFlexPLX, `adult1` = "adult")
MGFlexPLX[["merged.ident"]] <- Idents(object = MGFlexPLX)
Idents(object = MGFlexPLX) <- "names"
DimPlot(MGFlexPLX, cols = c("grey85", "yellowgreen", "violet", "yellow2", "brown3", "grey40", "red", "blue", "deepskyblue"), pt.size = 0.5, split.by = "merged.ident")

MGFlexPLX.markers %>%
group_by(cluster) %>%
slice_head(n = 10) %>%
ungroup() -> top10
DoHeatmap(MGFlexPLX, features = top10$gene, group.colors = c("grey85", "yellowgreen", "violet", "yellow2", "brown3", "grey45", "red", "blue", "deepskyblue"))

prop.table(table(Idents(MGFlexPLX), MGFlexPLX$orig.ident), margin = 2)

Idents(object = MGFlexPLX) <- "merged.ident"
merged.markers <- FindAllMarkers(MGFlexPLX, only.pos = TRUE)
merged.markers %>%
group_by(cluster) %>%
slice_head(n = 30) %>%
ungroup() -> top30

DoHeatmap(MGFlexPLX, features = top30$gene, group.colors = c("grey85", "grey45", "pink"))

DotPlot(MGFlexPLX, features = c("Csf1r", "P2ry12", "Tmem119", "Siglech", "Sall1"), cols = c("lightgrey", "darkgreen"), dot.scale = 10, col.min = -1, col.max = 2) + coord_flip()
DotPlot(MGFlexPLX, features = c("H2-D1", "Apoe", "Cd74", "Lpl", "Itgax"), cols = c("lightgrey", "darkorchid"), dot.scale = 10, col.min = -1, col.max = 2) + coord_flip()
DotPlot(MGFlexPLX, features = c("Cdkn1a", "Cdkn2a", "Mif", "Spp1", "Il1b"), cols = c("lightgrey", "darkorange"), dot.scale = 10, col.min = -1, col.max = 2, scale.min = 0) + coord_flip()
DotPlot(MGFlexPLX, features = c("Tlr2", "Csf2ra", "Ccl4", "Hif1a", "Pdcd1"), cols = c("lightgrey", "red"), dot.scale = 10, col.min = -1, col.max = 2) + coord_flip()
DotPlot(MGFlexPLX, features = c("Fth1", "Fau", "Npc2", "Tpt1", "Cd52"), cols = c("lightgrey", "blue"), dot.scale = 10, col.min = -1, col.max = 2) + coord_flip()
DotPlot(MGFlexPLX, features = c("Csf3r", "Fcgr3", "B2m", "Clec4a3", "Ly9"), cols = c("lightgrey", "deepskyblue"), dot.scale = 10, col.min = -1, col.max = 2, scale.min = 20) + coord_flip()

T.cells <- subset(FlexPLX, idents = "22")
VlnPlot(T.cells, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
T.cells <- FindVariableFeatures(T.cells, selection.method = "vst", nfeatures = 2000)
T.cells <- ScaleData(T.cells, features = all.genes)
T.cells <- RunPCA(T.cells, features = VariableFeatures(object = T.cells))
ElbowPlot(T.cells)
T.cells <- FindNeighbors(T.cells, dims = 1:10)
T.cells <- FindClusters(T.cells, resolution = 0.5)
T.cells <- RunUMAP(T.cells, dims = 1:10)
DimPlot(T.cells)
FeaturePlot(T.cells, features = "Cd3e")
FeaturePlot(T.cells, features = "Cd8a")
FeaturePlot(T.cells, features = "Cd4")
T.cells <- subset(T.cells, idents = c("0", "2", "3", "4", "7"))
T.cells <- FindNeighbors(T.cells, dims = 1:10)
T.cells <- FindClusters(T.cells, resolution = 1.0)
T.cells <- RunUMAP(T.cells, dims = 1:10)
T.cells.markers <- FindAllMarkers(T.cells, only.pos = TRUE)
FeaturePlot(T.cells, features = "Cd8a", cols = c("lightgrey", "red"), pt.size = 0.5)
FeaturePlot(T.cells, features = "Cd4", cols = c("lightgrey", "darkgreen"), pt.size = 0.5)
FeaturePlot(T.cells, features = "Cxcr3", cols = c("lightgrey", "red"), pt.size = 0.5)
FeaturePlot(T.cells, features = "Itga1", cols = c("lightgrey", "red"), pt.size = 0.5)
FeaturePlot(T.cells, features = "Tcf7", cols = c("lightgrey", "red"), pt.size = 0.5)
FeaturePlot(T.cells, features = "Sell", cols = c("lightgrey", "blue"), pt.size = 0.5)
Idents(object = T.cells) <- "orig.ident"
T.cells <- RenameIdents(object = T.cells, `agedPLX1` = "agedPLX")
T.cells <- RenameIdents(object = T.cells, `agedPLX2` = "agedPLX")
T.cells <- RenameIdents(object = T.cells, `aged2` = "aged")
T.cells <- RenameIdents(object = T.cells, `aged1` = "aged")
T.cells <- RenameIdents(object = T.cells, `adult2` = "adult")
T.cells <- RenameIdents(object = T.cells, `adult1` = "adult")
T.cells[["merged.ident"]] <- Idents(object = T.cells)
merged.markers <- FindAllMarkers(T.cells, only.pos = TRUE)
DotPlot(T.cells, features = c("Satb1", "Sell", "Ccr7", "Pdcd1", "Lag3", "Ctla4"), cols = c("lightgrey", "darkgreen"), scale.min = 0, dot.scale = 10)
DotPlot(T.cells, features = c("Cd8a", "Cxcr3", "Gzmb", "Cd4", "Eomes", "Ifng"), cols = c("lightgrey", "darkorchid"), dot.scale = 10, col.min = -1, col.max = 2, scale.min = 0)


